spring.application.name=dsprogram

# PostgreSQL Database Configuration
server.port=${PORT:8080}

spring.datasource.url=jdbc:${DATABASE_URL}


spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
# Email Configuration (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hirwa349@gmail.com
spring.mail.password=jsec yich qbxa xqnf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html
spring.thymeleaf.prefix=classpath:/templates/

# File upload limits - INCREASED TO 30MB
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

# Server Configuration


# Fix for driver detection
spring.sql.init.mode=never
